#! /bin/bash

#LOAD AT BOOT TO KEEP UPDATED

####################################################
## Wraiths System
## version 1.0
## version date: 03/01/2021
## By : VVirtualPhantom
####################################################

##################################
#Scans folder supplied and stores everything in it as non operational names
#whilst also expanding to any folders within to show whole folder structure
##################################


FolderScanner(){

#Find the working directory
	currentDirectory=$1
	declare -a wraithList=($(ls $currentDirectory))
	declare -a folderList=($(ls -d $currentDirectory/*/ | awk -F "$currentDirectory/" '{print $2}' | awk -F "/" '{print $1}'))
	directoryCheck=false

	for file in ${wraithList[@]}
	do
		echo $file
		for folder in ${folderList[@]}
		do
			#check which files are directories
			if [[ $file == $folder ]]
			then
			echo "FolderMatch"
			directoryCheck=true
			break
			else
			echo "noMatch"
			directoryCheck=false
			fi

		echo $directoryCheck
		done

		#opens directories as new submenus
		if [ $directoryCheck = true ]
		then
			echo "directory found"
			echo "[submenu] (${file})" >> /wraiths/menuDisplay.txt
			newFolder="$currentDirectory/$file"
			FolderScanner $newFolder
			echo "[end]" >> /wraiths/menuDisplay.txt
		elif [[ $file == "launch" ]]
		then
			echo "[exec] (Launch) {guake --show -n '$file' -e 'sudo $currentDirectory/$file'}" >> /wraiths/menuDisplay.txt	
		else
			echo "[nop] (${file})" >> /wraiths/menuDisplay.txt
		fi
	done

	if [ -z $wraithList ]
	then
	echo "[nop] (No Wraiths)" >> /wraiths/menuDisplay.txt
        fi
}


##############################
#set up main files to search in
##############################

echo "[submenu] (Wraiths) {}" >  /wraiths/menuDisplay.txt
echo "[exec] (Update) {/wraiths/wraithSearch &}" >> /wraiths/menuDisplay.txt
echo "[submenu] (Offensive) {/wraiths/offensive}" >> /wraiths/menuDisplay.txt

FolderScanner /wraiths/offensive

echo "[end]" >> /wraiths/menuDisplay.txt
echo "[submenu] (Recon) {/wraiths/recon}" >> /wraiths/menuDisplay.txt

FolderScanner /wraiths/recon

echo "[end]" >> /wraiths/menuDisplay.txt
echo ["submenu] (Passive) {/wraiths/passive}" >> /wraiths/menuDisplay.txt

FolderScanner /wraiths/passive

echo "[end]" >> /wraiths/menuDisplay.txt
echo "[end]" >> /wraiths/menuDisplay.txt
